### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by nealioa** [jacobl992/Portfolio#1]
index.html

line 11: Indented too far - due to being a tab rather than spaces. Change all tabs to spaces.

lines 87-89: Too many blank lines. Only have one.

aboutme.html

Same issues to index.html.

styles.css

line 194: Change `padding-top; 2vw` to `padding-top: 2vw;`

line 243: For consistency, hence better readibility, change `white` to its hex equivalent `#ffffff`.

Change
```
a:link {
	text-decoration: none;
}
a:visited {
	text-decoration: none;
}
a:hover {
	text-decoration: none;
}
a:active {
	text-decoration: none;
}
```
to
```
a:link,
a:visited,
a:hover,
a:active {
	text-decoration: none;
}
```

**Comment by jacobl992** [comment]
Thanks Neal, all changes have been added

**Comment by nealioa** [comment]
Thanks
